### ISSUE TITLE
Add missing links support.

### ISSUE THREAD

**Issue by davemackintosh** [newworldcode/waterline-jsonapi#4]
Currently, it's not JSON API compliant RE links.

**Comment by marcelklehr** [comment]
Hey, this is a life-saver! How can I help with pushing forward link support?

**Comment by davemackintosh** [comment]
It's actually on my "immediately todo" list :) got a couple of other FOSS releases but mid next week should see this land!

**Comment by marcelklehr** [comment]
Awesome! :)

**Comment by davemackintosh** [comment]
@marcelklehr This is also part of the new rebuild :)
