### ISSUE TITLE
Don't require populate

### ISSUE THREAD

**Issue by marcelklehr** [newworldcode/waterline-jsonapi#7]
Right now, it seems, waterline-jsonapi can't detect when a relation is not populated, i.e. if it's just an array of ids, it seems to try to `include` the related models failing with a reference error that id couldn't be found (not for top-level models, but e.g. if I pass a collection of models to new_from_values.)

For top-level models it would be nice if it would provide the `relationships`, even if they aren't populated.

**Comment by davemackintosh** [comment]
Could you make an example of the issue so I can clone/fix please @marcelklehr?

**Comment by marcelklehr** [comment]
```js
// GET /owners/1/relationship/pets
var owner = await Owner.findOne(1)
JSONAPI.new_from_values(owner.pets)
```
Expected response:
```json
{ "data": [
    { "type": "pet"
    , "id": "5"
    }
  , { "type": "pet"
    , "id": "7"
    }
  ]
}
```

Actual response:
of course, sorry...

Code
```json
{
    "errors": [
        {
            "id": "d84f7461-e36c-442e-959d-74b4581a7a74",
            "detail": "`id` is a required property for jsonapi compliancy."
        }
    ]
}
```

**Comment by davemackintosh** [comment]
That's a good find, I'll try to confirm over the next couple of days (big client project release this week) and come back to you.

**Comment by marcelklehr** [comment]
So, it seems, after investigation further, that this is, in part, a waterline issue. Unpopulated to-Many relations *do not* contain the IDs of the related entries. (due to the way dbms store and retrieve these entries). To-One relations do feature the related id, though, so the above example would now look like this:

Code:
```js
// GET /owners/1/relationship/pets
var pet = await Pet.findOne(1)
JSONAPI.new_from_values(pet)
```
Expected response:
```json
{ "data": {
   "type": "pet"
  , "id": "7"
  , "relationships": {
      "owner": {"data": {"type": "owner", "id": "1"}}
    }
  }
}
```

Actual response:

```json
{
    "errors": [
        {
            "id": "d84f7461-e36c-442e-959d-74b4581a7a74",
            "detail": "`id` is a required property for jsonapi compliancy."
        }
    ]
}
```

**Comment by davemackintosh** [comment]
@dylanswartz Could you try the latest version by using the git repo to test with, i.e `npm i git@github.com:newworldcode/waterline-jsonapi.git`

The module has been totally rewritten to support more of the spec, more accurately and with less bugs :) I'd really appreciate some testing.

**Comment by marcelklehr** [comment]
(I've since written up a little library that works for me and that's also easier (for me) to grok. See https://github.com/marcelklehr/waterline-to-jsonapi -- it has no tests yet, but has <200LOC and works in my scenarios...)

**Comment by davemackintosh** [comment]
Ahh, that's a shame but very cool. Thanks for letting me know!
